import { useEffect } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { CheckoutProgress } from '../../components/checkout/CheckoutProgress';
import { OrderSummary } from '../../components/checkout/OrderSummary';
import { PaymentForm } from '../../components/checkout/PaymentForm';
import { ShippingForm } from '../../components/checkout/ShippingForm';
import { useCart } from '../../features/cart/CartContext';
import { useCheckout, type CheckoutStep } from '../../features/checkout/CheckoutContext';
import { Button } from '../../components/ui/Button';

function getStep(pathname: string): CheckoutStep { if (pathname.endsWith('/payment')) return 'payment'; if (pathname.endsWith('/review')) return 'review'; return 'shipping'; }
export function CheckoutPage() { const location = useLocation(); const navigate = useNavigate(); const { items } = useCart(); const { step, setStep, shipping, payment } = useCheckout(); const routeStep = getStep(location.pathname); useEffect(() => { if (step !== routeStep) setStep(routeStep); }, [routeStep, setStep, step]); useEffect(() => { if (!items.length) navigate('/cart', { replace: true }); }, [items.length, navigate]); const submitOrder = () => { if (shipping && payment) navigate('/checkout/confirmation'); }; return <main className="checkout-page"><header className="checkout-header container"><Link className="wordmark" to="/">Falcon</Link><span className="secure-label">Secure checkout</span></header><div className="checkout-layout container"><div className="checkout-main"><CheckoutProgress current={routeStep} />{routeStep === 'shipping' && <section><p className="eyebrow">01 / Delivery</p><h1>Shipping information</h1><ShippingForm /></section>}{routeStep === 'payment' && <section><p className="eyebrow">02 / Payment</p><h1>Payment information</h1><PaymentForm /></section>}{routeStep === 'review' && <section><p className="eyebrow">03 / Confirmation</p><h1>Review your order</h1><div className="review-panel"><p>Shipping to {shipping.city || 'your selected address'}.</p><p>Your payment method has been securely prepared for this prototype.</p><Button onClick={submitOrder}>Place order</Button></div></section>}</div><OrderSummary compact /></div></main>; }